#!/usr/bin/env bash
# Requires a positive Buy Now price, updating only the Inventory API image.
# It never creates or changes Redis/ACL, never updates or starts a job, and never runs DDL, Sync, or a projection rebuild.
set -Eeuo pipefail

readonly RESOURCE_GROUP="rg-lsc-inventory-prod"
readonly REGISTRY_NAME="acrlscinvprodeus2"
readonly REGISTRY_LOGIN_SERVER="acrlscinvprodeus2.azurecr.io"
readonly IMAGE_REPOSITORY="lsc-inventory-engine"
readonly IMAGE_TAG="inventory-api-integrated-r69-buy-now-positive"
readonly API_NAME="ca-lsc-inventory-api-prod"
readonly REDIS_NAME="lsc-inventory-facets-redis"
readonly REDIS_DATABASE_NAME="default"
readonly REDIS_ENDPOINT="${REDIS_NAME}.eastus2.redis.azure.net:10000"
readonly API_RUNTIME_IDENTITY_NAME="id-lsc-inventory-db-runtime-prod"
readonly IAAI_JOB_NAME="job-lsc-iaai-pilot-prod"
readonly COPART_JOB_NAME="job-lsc-copart-excel-prod"
readonly COPART_AUTO_JOB_NAME="job-lsc-copart-auto-prod"
readonly GENERIC_JOB_NAME="job-lsc-inventory-ingestion-prod"
readonly SCORING_JOB_NAME="job-lsc-inventory-scoring-prod"
readonly EXPECTED_API_IMAGE="${REGISTRY_LOGIN_SERVER}/${IMAGE_REPOSITORY}:inventory-api-integrated-r68-title-rebuild-sql-fix"
readonly EXPECTED_IAAI_IMAGE="${REGISTRY_LOGIN_SERVER}/${IMAGE_REPOSITORY}:iaai-cursor-recovery-r14"
readonly EXPECTED_SCORING_IMAGE="${REGISTRY_LOGIN_SERVER}/${IMAGE_REPOSITORY}:inventory-api-integrated-r54-queue-claim-fairness"
readonly EXPECTED_IAAI_CRON="15,45 * * * *"
readonly EXPECTED_COPART_AUTO_IMAGE="${REGISTRY_LOGIN_SERVER}/${IMAGE_REPOSITORY}:copart-cdbac2d0c0f3add67e5a7634f8ca629bbad90c08"
readonly EXPECTED_COPART_AUTO_CRON="0,30 * * * *"
readonly EXPECTED_COPART_AUTO_ARGS='["--copart-excel-run"]'
readonly EXPECTED_SCORING_CRON="7,22,37,52 * * * *"
readonly EXPECTED_SCORING_ARGS='["--scoring-backfill"]'
readonly SOURCE_CONTEXT_URL="https://github.com/cococelgit/LSCInventoryCopartIaaI.git#8c2fd0c08d28ffa08aea76e4df9ee244bf610949"

fail() { printf 'API_R69_BUY_NOW_POSITIVE_ERROR: %s\n' "$*" >&2; exit 1; }
app_field() { az containerapp show --resource-group "$RESOURCE_GROUP" --name "$API_NAME" --query "$1" --output tsv; }
job_field() { az containerapp job show --resource-group "$RESOURCE_GROUP" --name "$1" --query "$2" --output tsv; }
fingerprint_app() { az containerapp show --resource-group "$RESOURCE_GROUP" --name "$API_NAME" --query "$1" --output json | sha256sum | { read -r digest _; printf '%s\n' "$digest"; }; }
fingerprint_job() { local job_name="$1" query="$2"; az containerapp job show --resource-group "$RESOURCE_GROUP" --name "$job_name" --query "$query" --output json | sha256sum | { read -r digest _; printf '%s\n' "$digest"; }; }
app_env_value() { app_field "properties.template.containers[0].env[?name=='$1'].value | [0]"; }
app_env_hash() { az containerapp show --resource-group "$RESOURCE_GROUP" --name "$API_NAME" --query 'properties.template.containers[0].env' --output json | jq -S | sha256sum | { read -r digest _; printf '%s\n' "$digest"; }; }
app_env_without_redis_hash() { az containerapp show --resource-group "$RESOURCE_GROUP" --name "$API_NAME" --query 'properties.template.containers[0].env' --output json | jq -S 'map(select(.name | startswith("FacetsRedis__") | not))' | sha256sum | { read -r digest _; printf '%s\n' "$digest"; }; }
compact_job_json() { az containerapp job show --resource-group "$RESOURCE_GROUP" --name "$1" --query "$2" --output json | tr -d '[:space:]'; }
command -v az >/dev/null 2>&1 || fail "Azure CLI is unavailable"
command -v curl >/dev/null 2>&1 || fail "curl is unavailable"
command -v jq >/dev/null 2>&1 || fail "jq is unavailable"
command -v sha256sum >/dev/null 2>&1 || fail "sha256sum is unavailable"
az extension add --name containerapp --upgrade --only-show-errors

api_image_before="$(app_field 'properties.template.containers[0].image')"
api_mode_before="$(app_field properties.configuration.activeRevisionsMode)"
api_identity_before="$(fingerprint_app identity)"
api_secrets_before="$(fingerprint_app properties.configuration.secrets)"
api_ingress_before="$(fingerprint_app properties.configuration.ingress)"
api_scale_before="$(fingerprint_app properties.template.scale)"
api_env_before="$(app_env_hash)"
api_env_without_redis_before="$(app_env_without_redis_hash)"
api_sync_before="$(app_env_value Sync__Enabled)"
api_migrations_before="$(app_env_value Persistence__RunMigrations)"
api_warmup_before="$(app_env_value SearchProjection__WarmupOnStartup)"
api_redis_enabled_before="$(app_env_value FacetsRedis__Enabled)"
api_redis_endpoint_before="$(app_env_value FacetsRedis__Endpoint)"
api_redis_identity_before="$(app_env_value FacetsRedis__ManagedIdentityClientId)"
api_identity_id="$(app_field 'keys(identity.userAssignedIdentities)[0]')"
[[ -n "$api_identity_id" && "$api_identity_id" != "null" ]] || fail "Unable to resolve API managed identity"
[[ "$api_identity_id" == */userAssignedIdentities/${API_RUNTIME_IDENTITY_NAME} ]] || fail "API managed identity differs from the approved Redis ACL principal"
api_identity_client_id="$(az identity show --ids "$api_identity_id" --query clientId --output tsv)"
api_identity_object_id="$(az identity show --ids "$api_identity_id" --query principalId --output tsv)"
[[ -n "$api_identity_client_id" && "$api_identity_client_id" != "null" && -n "$api_identity_object_id" && "$api_identity_object_id" != "null" ]] || fail "Unable to resolve API managed identity identifiers"

iaai_image_before="$(job_field "$IAAI_JOB_NAME" 'properties.template.containers[0].image')"
iaai_trigger_before="$(job_field "$IAAI_JOB_NAME" properties.configuration.triggerType)"
iaai_cron_before="$(job_field "$IAAI_JOB_NAME" properties.configuration.scheduleTriggerConfig.cronExpression)"
iaai_template_before="$(fingerprint_job "$IAAI_JOB_NAME" properties.template)"
iaai_configuration_before="$(fingerprint_job "$IAAI_JOB_NAME" properties.configuration)"
iaai_identity_before="$(fingerprint_job "$IAAI_JOB_NAME" identity)"
copart_template_before="$(fingerprint_job "$COPART_JOB_NAME" properties.template)"
copart_configuration_before="$(fingerprint_job "$COPART_JOB_NAME" properties.configuration)"
copart_identity_before="$(fingerprint_job "$COPART_JOB_NAME" identity)"
copart_auto_args_before="$(compact_job_json "$COPART_AUTO_JOB_NAME" 'properties.template.containers[0].args')"
copart_auto_image_before="$(job_field "$COPART_AUTO_JOB_NAME" 'properties.template.containers[0].image')"
copart_auto_trigger_before="$(job_field "$COPART_AUTO_JOB_NAME" properties.configuration.triggerType)"
copart_auto_cron_before="$(job_field "$COPART_AUTO_JOB_NAME" properties.configuration.scheduleTriggerConfig.cronExpression)"
copart_auto_template_before="$(fingerprint_job "$COPART_AUTO_JOB_NAME" properties.template)"
copart_auto_configuration_before="$(fingerprint_job "$COPART_AUTO_JOB_NAME" properties.configuration)"
copart_auto_identity_before="$(fingerprint_job "$COPART_AUTO_JOB_NAME" identity)"
generic_trigger_before="$(job_field "$GENERIC_JOB_NAME" properties.configuration.triggerType)"
generic_template_before="$(fingerprint_job "$GENERIC_JOB_NAME" properties.template)"
generic_configuration_before="$(fingerprint_job "$GENERIC_JOB_NAME" properties.configuration)"
generic_identity_before="$(fingerprint_job "$GENERIC_JOB_NAME" identity)"
scoring_image_before="$(job_field "$SCORING_JOB_NAME" 'properties.template.containers[0].image')"
scoring_trigger_before="$(job_field "$SCORING_JOB_NAME" properties.configuration.triggerType)"
scoring_cron_before="$(job_field "$SCORING_JOB_NAME" properties.configuration.scheduleTriggerConfig.cronExpression)"
scoring_args_before="$(compact_job_json "$SCORING_JOB_NAME" 'properties.template.containers[0].args')"
scoring_template_before="$(fingerprint_job "$SCORING_JOB_NAME" properties.template)"
scoring_configuration_before="$(fingerprint_job "$SCORING_JOB_NAME" properties.configuration)"
scoring_identity_before="$(fingerprint_job "$SCORING_JOB_NAME" identity)"

[[ "$api_image_before" == "$EXPECTED_API_IMAGE" ]] || fail "Expected r68 title rebuild SQL API image; found: ${api_image_before:-empty}"
[[ "$api_mode_before" == "Single" ]] || fail "Expected API Single revision mode; found: ${api_mode_before:-empty}"
[[ "$api_sync_before" == "false" ]] || fail "Expected Sync__Enabled=false; found: ${api_sync_before:-empty}"
[[ "$api_migrations_before" == "false" ]] || fail "Expected Persistence__RunMigrations=false; found: ${api_migrations_before:-empty}"
[[ "$api_warmup_before" == "true" ]] || fail "Expected SearchProjection__WarmupOnStartup=true; found: ${api_warmup_before:-empty}"
[[ "$api_redis_enabled_before" == "true" && "$api_redis_endpoint_before" == "$REDIS_ENDPOINT" && "$api_redis_identity_before" == "$api_identity_client_id" ]] || fail "Expected existing FacetsRedis configuration to remain intact"
[[ "$iaai_image_before" == "$EXPECTED_IAAI_IMAGE" ]] || fail "Expected IAAI r14 image; found: ${iaai_image_before:-empty}"
[[ "$iaai_trigger_before" == "Schedule" && "$iaai_cron_before" == "$EXPECTED_IAAI_CRON" ]] || fail "IAAI trigger or cron changed unexpectedly"
[[ "$copart_auto_image_before" == "$EXPECTED_COPART_AUTO_IMAGE" ]] || fail "Expected approved Copart inline scoring image; found: ${copart_auto_image_before:-empty}"
[[ "$copart_auto_trigger_before" == "Schedule" && "$copart_auto_cron_before" == "$EXPECTED_COPART_AUTO_CRON" ]] || fail "Copart automatic trigger or cron changed unexpectedly"
[[ "$copart_auto_args_before" == "$EXPECTED_COPART_AUTO_ARGS" ]] || fail "Copart automatic arguments changed unexpectedly"
[[ "$generic_trigger_before" == "Manual" ]] || fail "Expected generic job to remain Manual; found: ${generic_trigger_before:-empty}"
[[ "$scoring_image_before" == "$EXPECTED_SCORING_IMAGE" ]] || fail "Expected scoring r54 image; found: ${scoring_image_before:-empty}"
[[ "$scoring_trigger_before" == "Schedule" && "$scoring_cron_before" == "$EXPECTED_SCORING_CRON" && "$scoring_args_before" == "$EXPECTED_SCORING_ARGS" ]] || fail "Scoring configuration changed unexpectedly"

image_ref="${REGISTRY_LOGIN_SERVER}/${IMAGE_REPOSITORY}:${IMAGE_TAG}"
printf 'API_R69_BUILD_START image=%s git_context=%s\n' "$image_ref" "$SOURCE_CONTEXT_URL"
az acr build --registry "$REGISTRY_NAME" --image "${IMAGE_REPOSITORY}:${IMAGE_TAG}" --file Dockerfile "$SOURCE_CONTEXT_URL"
printf 'API_R69_UPDATE_START\n'
if ! az containerapp update --resource-group "$RESOURCE_GROUP" --name "$API_NAME" --image "$image_ref" --output none; then
  printf 'API_R68_UPDATE_POLLING_RETRY: Azure CLI lost its operation-poll connection; verifying the submitted update directly.\n' >&2
  sleep 20
fi

api_image_after="$(app_field 'properties.template.containers[0].image')"
api_revision_after="$(app_field properties.latestRevisionName)"
api_ready_after="$(app_field properties.latestReadyRevisionName)"
api_mode_after="$(app_field properties.configuration.activeRevisionsMode)"
api_identity_after="$(fingerprint_app identity)"
api_secrets_after="$(fingerprint_app properties.configuration.secrets)"
api_ingress_after="$(fingerprint_app properties.configuration.ingress)"
api_scale_after="$(fingerprint_app properties.template.scale)"
api_env_after="$(app_env_hash)"
api_env_without_redis_after="$(app_env_without_redis_hash)"
api_sync_after="$(app_env_value Sync__Enabled)"
api_migrations_after="$(app_env_value Persistence__RunMigrations)"
api_warmup_after="$(app_env_value SearchProjection__WarmupOnStartup)"
api_redis_enabled_after="$(app_env_value FacetsRedis__Enabled)"
api_redis_endpoint_after="$(app_env_value FacetsRedis__Endpoint)"
api_redis_identity_after="$(app_env_value FacetsRedis__ManagedIdentityClientId)"
api_state_after="$(az containerapp revision list --resource-group "$RESOURCE_GROUP" --name "$API_NAME" --query "[?name=='${api_revision_after}'].properties.runningState | [0]" --output tsv)"
api_fqdn="$(app_field properties.configuration.ingress.fqdn)"
iaai_image_after="$(job_field "$IAAI_JOB_NAME" 'properties.template.containers[0].image')"
iaai_trigger_after="$(job_field "$IAAI_JOB_NAME" properties.configuration.triggerType)"
iaai_cron_after="$(job_field "$IAAI_JOB_NAME" properties.configuration.scheduleTriggerConfig.cronExpression)"
iaai_template_after="$(fingerprint_job "$IAAI_JOB_NAME" properties.template)"
iaai_configuration_after="$(fingerprint_job "$IAAI_JOB_NAME" properties.configuration)"
iaai_identity_after="$(fingerprint_job "$IAAI_JOB_NAME" identity)"
copart_template_after="$(fingerprint_job "$COPART_JOB_NAME" properties.template)"
copart_configuration_after="$(fingerprint_job "$COPART_JOB_NAME" properties.configuration)"
copart_identity_after="$(fingerprint_job "$COPART_JOB_NAME" identity)"
copart_auto_args_after="$(compact_job_json "$COPART_AUTO_JOB_NAME" 'properties.template.containers[0].args')"
copart_auto_image_after="$(job_field "$COPART_AUTO_JOB_NAME" 'properties.template.containers[0].image')"
copart_auto_trigger_after="$(job_field "$COPART_AUTO_JOB_NAME" properties.configuration.triggerType)"
copart_auto_cron_after="$(job_field "$COPART_AUTO_JOB_NAME" properties.configuration.scheduleTriggerConfig.cronExpression)"
copart_auto_template_after="$(fingerprint_job "$COPART_AUTO_JOB_NAME" properties.template)"
copart_auto_configuration_after="$(fingerprint_job "$COPART_AUTO_JOB_NAME" properties.configuration)"
copart_auto_identity_after="$(fingerprint_job "$COPART_AUTO_JOB_NAME" identity)"
generic_trigger_after="$(job_field "$GENERIC_JOB_NAME" properties.configuration.triggerType)"
generic_template_after="$(fingerprint_job "$GENERIC_JOB_NAME" properties.template)"
generic_configuration_after="$(fingerprint_job "$GENERIC_JOB_NAME" properties.configuration)"
generic_identity_after="$(fingerprint_job "$GENERIC_JOB_NAME" identity)"
scoring_image_after="$(job_field "$SCORING_JOB_NAME" 'properties.template.containers[0].image')"
scoring_trigger_after="$(job_field "$SCORING_JOB_NAME" properties.configuration.triggerType)"
scoring_cron_after="$(job_field "$SCORING_JOB_NAME" properties.configuration.scheduleTriggerConfig.cronExpression)"
scoring_args_after="$(compact_job_json "$SCORING_JOB_NAME" 'properties.template.containers[0].args')"
scoring_template_after="$(fingerprint_job "$SCORING_JOB_NAME" properties.template)"
scoring_configuration_after="$(fingerprint_job "$SCORING_JOB_NAME" properties.configuration)"
scoring_identity_after="$(fingerprint_job "$SCORING_JOB_NAME" identity)"

[[ "$api_image_after" == "$image_ref" ]] || fail "API image was not updated to r69 Buy Now positive build"
[[ "$api_mode_after" == "$api_mode_before" && "$api_identity_after" == "$api_identity_before" && "$api_secrets_after" == "$api_secrets_before" && "$api_ingress_after" == "$api_ingress_before" && "$api_scale_after" == "$api_scale_before" && "$api_env_after" == "$api_env_before" && "$api_env_without_redis_after" == "$api_env_without_redis_before" && "$api_sync_after" == "$api_sync_before" && "$api_migrations_after" == "$api_migrations_before" && "$api_warmup_after" == "$api_warmup_before" ]] || fail "API configuration changed unexpectedly"
[[ "$api_redis_enabled_after" == "$api_redis_enabled_before" && "$api_redis_endpoint_after" == "$api_redis_endpoint_before" && "$api_redis_identity_after" == "$api_redis_identity_before" ]] || fail "API Redis configuration changed unexpectedly"
[[ "$iaai_image_after" == "$iaai_image_before" && "$iaai_trigger_after" == "$iaai_trigger_before" && "$iaai_cron_after" == "$iaai_cron_before" && "$iaai_template_after" == "$iaai_template_before" && "$iaai_configuration_after" == "$iaai_configuration_before" && "$iaai_identity_after" == "$iaai_identity_before" ]] || fail "IAAI job changed unexpectedly"
[[ "$copart_template_after" == "$copart_template_before" && "$copart_configuration_after" == "$copart_configuration_before" && "$copart_identity_after" == "$copart_identity_before" ]] || fail "Copart Excel job changed unexpectedly"
[[ "$copart_auto_image_after" == "$copart_auto_image_before" && "$copart_auto_trigger_after" == "$copart_auto_trigger_before" && "$copart_auto_cron_after" == "$copart_auto_cron_before" && "$copart_auto_args_after" == "$copart_auto_args_before" && "$copart_auto_template_after" == "$copart_auto_template_before" && "$copart_auto_configuration_after" == "$copart_auto_configuration_before" && "$copart_auto_identity_after" == "$copart_auto_identity_before" ]] || fail "Scheduled Copart auto job changed unexpectedly"
[[ "$generic_trigger_after" == "$generic_trigger_before" && "$generic_template_after" == "$generic_template_before" && "$generic_configuration_after" == "$generic_configuration_before" && "$generic_identity_after" == "$generic_identity_before" ]] || fail "Generic job changed unexpectedly"
[[ "$scoring_image_after" == "$scoring_image_before" && "$scoring_trigger_after" == "$scoring_trigger_before" && "$scoring_cron_after" == "$scoring_cron_before" && "$scoring_args_after" == "$scoring_args_before" && "$scoring_template_after" == "$scoring_template_before" && "$scoring_configuration_after" == "$scoring_configuration_before" && "$scoring_identity_after" == "$scoring_identity_before" ]] || fail "Scoring job changed unexpectedly"

curl --fail --silent --show-error --retry 12 --retry-delay 5 "https://${api_fqdn}/healthz" >/dev/null || fail "New API revision did not pass healthz"
printf 'API_R69_BUY_NOW_POSITIVE_DEPLOY_COMPLETED\nAPI_IMAGE=%s\nAPI_REVISION=%s\nAPI_READY_REVISION=%s\nAPI_STATE=%s\nREDIS_NAME=%s\nREDIS_ENDPOINT=%s\nREDIS_HA=Disabled\nREDIS_ACCESS_KEYS_ENABLED=false\n' "$api_image_after" "$api_revision_after" "$api_ready_after" "$api_state_after" "$REDIS_NAME" "$REDIS_ENDPOINT"
printf 'IAAI_JOB_CHANGED=false\nCOPART_JOB_CHANGED=false\nCOPART_AUTO_JOB_CHANGED=false\nGENERIC_JOB_CHANGED=false\nSCORING_JOB_CHANGED=false\nJOB_EXECUTION_STARTED=false\nCOPART_APIBARA_ENABLED=false\nMIGRATIONS_ENABLED=false\nFACET_INDEX_MIGRATION_STARTED=false\nPROJECTION_REBUILD_STARTED=false\n'
