#!/usr/bin/env python3
"""Generate the Copart title-code catalog from the user-provided PDF text extraction."""
from __future__ import annotations

import re
import sys
from pathlib import Path

ENTRY = re.compile(r"^\s*\f?([A-Z0-9]{1,3})\s{2,}(.+?)\s{2,}(.+?)\s{2,}(si|no)(?:\s+.*)?$", re.IGNORECASE)
MANUAL = {
    "B1": ("Salvage/Rebuilt Title Variant", "Variante de título de salvamento o reconstruido según el estado", True),
    "B2": ("Salvage/Rebuilt Title Variant", "Variante de título de salvamento o reconstruido según el estado", True),
    "B3": ("Salvage/Rebuilt Title Variant", "Variante de título de salvamento o reconstruido según el estado", True),
}


def esc(value: str) -> str:
    return value.replace('\\', '\\\\').replace('"', '\\"')


def main() -> None:
    if len(sys.argv) != 3:
        raise SystemExit("usage: generate_copart_title_catalog.py <pdf-text-path> <target-cs-path>")
    parsed: dict[str, tuple[str, str, bool]] = {}
    for line in Path(sys.argv[1]).read_text(encoding="utf-8", errors="replace").splitlines():
        match = ENTRY.match(line)
        if not match:
            continue
        code, english, spanish, process = match.groups()
        parsed[code.upper()] = (english.strip(), spanish.strip(), process.lower() == "si")
    parsed.update(MANUAL)
    entries = "\n".join(
        f'        ["{code}"] = new("{code}", "{esc(english)}", "{esc(spanish)}", {str(process).lower()}),'
        for code, (english, spanish, process) in sorted(parsed.items())
    )
    target = f'''// <auto-generated />\n#nullable enable\n// Source: user-provided Títulos.pdf. Regenerate with tools/generate_copart_title_catalog.py.\nnamespace Lsc.Inventory.Api.Sources;\n\npublic sealed record CopartTitleDefinition(\n    string Code,\n    string EnglishDescription,\n    string SpanishDescription,\n    bool SourceProcessRecommendation);\n\npublic static class CopartTitleCatalog\n{{\n    public const string Version = "copart-titles-pdf-2026-08";\n\n    private static readonly IReadOnlyDictionary<string, CopartTitleDefinition> Definitions =\n        new Dictionary<string, CopartTitleDefinition>(StringComparer.OrdinalIgnoreCase)\n        {{\n{entries}\n        }};\n\n    public static bool TryGet(string? code, out CopartTitleDefinition definition)\n    {{\n        if (!string.IsNullOrWhiteSpace(code) && Definitions.TryGetValue(code.Trim(), out var found) && found is not null)\n        {{\n            definition = found;\n            return true;\n        }}\n\n        definition = default!;\n        return false;\n    }}\n}}\n'''
    Path(sys.argv[2]).write_text(target, encoding="utf-8")
    print(f"generated {len(parsed)} title definitions")


if __name__ == "__main__":
    main()
